"""initial migration

Revision ID: 9df524d579c5
Revises: 
Create Date: 2018-04-21 21:21:58.539183

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9df524d579c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bidders',
                    sa.Column('ProjID', sa.String(length=100), nullable=False),
                    sa.Column('Biders', sa.String(length=25), nullable=True),
                    sa.Column('FinalPrice', sa.String(length=10), nullable=True),
                    sa.Column('IsQualified', sa.String(length=5), nullable=True),
                    sa.Column('TechnicalScore', sa.String(length=5), nullable=True),
                    sa.Column('BusinessScore', sa.String(length=5), nullable=True),
                    sa.Column('PriceScore', sa.String(length=5), nullable=True),
                    sa.Column('TotalScore', sa.String(length=5), nullable=True),
                    sa.Column('Rank', sa.String(length=5), nullable=True),
                    sa.PrimaryKeyConstraint('ProjID')
                    )
    op.create_table('bidnotice',
                    sa.Column('ProjID', sa.String(length=100), nullable=False),
                    sa.Column('ProjTitle', sa.String(length=100), nullable=True),
                    sa.Column('ProjBud', sa.String(length=10), nullable=True),
                    sa.Column('PurMethod', sa.String(length=10), nullable=True),
                    sa.Column('SBs', sa.String(length=40), nullable=True),
                    sa.Column('QuoteDetail', sa.String(length=150), nullable=True),
                    sa.Column('ServiceReq', sa.String(length=50), nullable=True),
                    sa.Column('Quantity', sa.String(length=5), nullable=True),
                    sa.Column('Currency', sa.String(length=5), nullable=True),
                    sa.Column('UnitPrice', sa.String(length=10), nullable=True),
                    sa.Column('FinalPrice', sa.String(length=10), nullable=True),
                    sa.Column('ReviewDate', sa.Date(), nullable=True),
                    sa.Column('ReviewAddr', sa.String(length=40), nullable=True),
                    sa.Column('Attachment', sa.String(length=50), nullable=True),
                    sa.Column('ReviewCommittee', sa.String(length=30), nullable=True),
                    sa.Column('Manager', sa.String(length=25), nullable=True),
                    sa.Column('ReviewComment', sa.String(length=250), nullable=True),
                    sa.Column('AnnounceDDL', sa.Date(), nullable=True),
                    sa.PrimaryKeyConstraint('ProjID')
                    )
    op.create_table('correctionnotice',
                    sa.Column('ProjID', sa.String(length=100), nullable=False),
                    sa.Column('Content', sa.String(length=1000), nullable=True),
                    sa.PrimaryKeyConstraint('ProjID')
                    )
    op.create_table('focusproject',
                    sa.Column('ProjID', sa.String(length=100), nullable=False),
                    sa.Column('Title', sa.String(length=100), nullable=True),
                    sa.Column('Time', sa.Date(), nullable=True),
                    sa.PrimaryKeyConstraint('ProjID')
                    )
    op.create_table('procurementnotices',
                    sa.Column('ProjID', sa.String(length=100), nullable=False),
                    sa.Column('ProjTitle', sa.String(length=100), nullable=True),
                    sa.Column('City', sa.String(length=10), nullable=True),
                    sa.Column('ProjBud', sa.String(length=10), nullable=True),
                    sa.Column('PurQuantity', sa.String(length=5), nullable=True),
                    sa.Column('ProjReqURL', sa.String(length=50), nullable=True),
                    sa.Column('SupplierQuals', sa.String(length=50), nullable=True),
                    sa.Column('DDL', sa.Date(), nullable=True),
                    sa.Column('AnnunceDDL', sa.Date(), nullable=True),
                    sa.Column('BidStartTime', sa.Date(), nullable=True),
                    sa.Column('PubDate', sa.Date(), nullable=True),
                    sa.Column('Addr', sa.String(length=40), nullable=True),
                    sa.Column('BidStartAddr', sa.String(length=40), nullable=True),
                    sa.Column('BidBond', sa.String(length=10), nullable=True),
                    sa.Column('Publisher', sa.String(length=40), nullable=True),
                    sa.Column('Attachment', sa.String(length=50), nullable=True),
                    sa.PrimaryKeyConstraint('ProjID')
                    )
    op.create_table('purchasers',
                    sa.Column('ProjID', sa.String(length=100), nullable=False),
                    sa.Column('Purchaser', sa.String(length=50), nullable=True),
                    sa.Column('Contacts', sa.String(length=50), nullable=True),
                    sa.Column('ProjContacts', sa.String(length=10), nullable=True),
                    sa.Column('ProjTel', sa.String(length=20), nullable=True),
                    sa.Column('Fax', sa.String(length=20), nullable=True),
                    sa.Column('ZipCode', sa.String(length=15), nullable=True),
                    sa.PrimaryKeyConstraint('ProjID')
                    )
    op.create_table('purchasingagents',
                    sa.Column('ProjID', sa.String(length=100), nullable=False),
                    sa.Column('Agency', sa.String(length=50), nullable=True),
                    sa.Column('AgencyAddr', sa.String(length=50), nullable=True),
                    sa.Column('Contacts', sa.String(length=50), nullable=True),
                    sa.Column('ProjContacts', sa.String(length=10), nullable=True),
                    sa.Column('ContactsPhone', sa.String(length=20), nullable=True),
                    sa.Column('Fax', sa.String(length=20), nullable=True),
                    sa.Column('ZipCode', sa.String(length=15), nullable=True),
                    sa.PrimaryKeyConstraint('ProjID')
                    )
    op.create_table('user_focusproject',
                    sa.Column('UUID', sa.String(length=40), nullable=False),
                    sa.Column('ProjID', sa.String(length=200), nullable=False),
                    sa.PrimaryKeyConstraint('UUID')
                    )
    op.create_table('users',
                    sa.Column('UUID', sa.String(length=40), nullable=False),
                    sa.Column('UserName', sa.String(length=40), nullable=False),
                    sa.Column('Password', sa.String(length=32), nullable=False),
                    sa.Column('Gender', sa.String(length=2), nullable=False),
                    sa.Column('Birthday', sa.Date(), nullable=False),
                    sa.Column('Email', sa.String(length=20), nullable=False),
                    sa.Column('TelePhone', sa.String(length=18), nullable=False),
                    sa.Column('Activated', sa.BOOLEAN(), nullable=False),
                    sa.Column('RegDate', sa.Date(), nullable=False),
                    sa.Column('LastLogin', sa.Date(), nullable=True),
                    sa.PrimaryKeyConstraint('UUID'),
                    sa.UniqueConstraint('Email'),
                    sa.UniqueConstraint('UserName')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_focusproject')
    op.drop_table('purchasingagents')
    op.drop_table('purchasers')
    op.drop_table('procurementnotices')
    op.drop_table('focusproject')
    op.drop_table('correctionnotice')
    op.drop_table('bidnotice')
    op.drop_table('bidders')
    # ### end Alembic commands ###
