"""empty message

Revision ID: fd0f05290c28
Revises: 9df524d579c5
Create Date: 2018-04-24 19:57:18.975489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd0f05290c28'
down_revision = '9df524d579c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('administrator')
    op.add_column('bidnotice', sa.Column('City', sa.String(length=10), nullable=True))
    op.add_column('correctionnotice', sa.Column('City', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('correctionnotice', 'City')
    op.drop_column('bidnotice', 'City')
    op.create_table('administrator',
                    sa.Column('ID', mysql.VARCHAR(length=40), nullable=False),
                    sa.Column('Name', mysql.VARCHAR(length=40), nullable=False),
                    sa.Column('Password', mysql.VARCHAR(length=32), nullable=False),
                    sa.Column('State', mysql.VARCHAR(length=8), nullable=False),
                    sa.Column('RegisterTime', mysql.DATETIME(), nullable=False),
                    sa.Column('LastTime', mysql.DATETIME(), nullable=False),
                    sa.Column('Authorization', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"),
                              autoincrement=False, nullable=False),
                    mysql_default_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    # ### end Alembic commands ###
